name: Centrele ARES
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5442885686643422
title: Coronarografia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6328840518835932
  lightness: 0.8595765782520175
  saturation: 0.28186424542218447
  rhythmicContrast: 0.17862188047729433
purpose: []
